###############################################
# library init
###############################################

# rbenv init
if type rbenv > /dev/null 2>&1; then
  echo "setting up rbenv"
  eval "$(rbenv init -)"
fi

# direnv init
if type direnv > /dev/null 2>&1; then
  echo "setting up direnv"
  eval "$(direnv hook bash)"
fi

